'use strict';

// Auto-generated by: npm run extension:config
// Do not edit manually.

globalThis.REDLINE_EXTENSION_CONFIG = Object.freeze({
  supabaseUrl: "SUPABASE_URL_PLACEHOLDER",
  supabaseAnonKey: "SUPABASE_ANON_KEY_PLACEHOLDER",
});
